### ISSUE TITLE
[D] [Criação da Interface] Interface de gerenciamento de palavra sinônimos

### ISSUE THREAD

**Issue by cesarpelogia** [Morpheus-Fatec/morpheus#35]
# Descrição:

Como analista, desejo que a aplicação trate sinônimos de tags, para que possamos contemplar regionalismos nos textos e garantir uma categorização mais abrangente e precisa.

### Cadastro de Tags e Sinônimos:

- A interface deve permitir o cadastro de novas tags e suas listas de sinônimos.
- O usuário deve poder inserir múltiplos sinônimos para cada tag cadastrada.

### Visualização de Tags:

- A interface deve exibir uma lista de tags cadastradas, mostrando a relação de sinônimos para cada tag.

### Edição de Tags:

- A interface deve permitir editar as tags cadastradas, incluindo a adição e remoção de sinônimos.

### Remoção de Tags:

- A interface deve permitir a remoção de tags e seus sinônimos associados.
- Uma confirmação deve ser exibida antes de excluir qualquer tag.

## Tarefas:

**Cadastro de Tags e Sinônimos:**

- [x] Implementar a interface para permitir o cadastro de novas tags.
- [x] Implementar a interface para permitir o cadastro de listas de sinônimos para cada tag.
- [x] Permitir ao usuário inserir múltiplos sinônimos para cada tag cadastrada.

**Visualização de Tags:**

- [x] Implementar a interface para exibir uma lista de tags cadastradas.
- [x] Mostrar a relação de sinônimos para cada tag na lista.

**Edição de Tags:**

- [x] Implementar a interface para permitir a edição das tags cadastradas.
- [x] Permitir a adição de novos sinônimos para as tags existentes.
- [x] Permitir a remoção de sinônimos das tags existentes.

**Remoção de Tags:**

- [x] Implementar a interface para permitir a remoção de tags cadastradas.
- [x] Implementar a interface para permitir a remoção dos sinônimos associados às tags.
- [x] Exibir uma confirmação antes de excluir qualquer tag e seus sinônimos associados.

## Wireframes:

![Wireframe cadastro sinônimos](https://github.com/user-attachments/assets/7e78cc74-ffb1-4781-82ab-3427caadb5b6)

![Wireframe cadastro sinônimos 2](https://github.com/user-attachments/assets/0f653049-1b84-4ed7-96dc-2203795198c9)

**Comment by lucasnadalete** [comment]
Pessoal, criem a PR para o CR deste item.
