### ISSUE TITLE
[Aprimoramento Técnico] Revisão do Banco de Dados

### ISSUE THREAD

**Issue by cesarpelogia** [Morpheus-Fatec/morpheus#93]
# Descrição:

Realizar a revisão do banco de dados do projeto, garantindo que a estrutura esteja adequada, as tabelas estejam normalizadas, e as consultas sejam otimizadas para um desempenho eficiente e consistente com os requisitos do sistema.

### Estrutura do Banco de Dados:

- Verificar se as tabelas estão normalizadas de acordo com as boas práticas (até a 3ª forma normal, quando aplicável).

- Confirmar que os tipos de dados das colunas são adequados para os dados armazenados.

- Verificar se as chaves primárias e estrangeiras estão corretamente configuradas para garantir a integridade dos dados.

### Índices e Performance:

- Analisar a necessidade de criação ou remoção de índices para otimizar as consultas mais frequentes.

### Consistência e Integridade:

- Garantir que as restrições de integridade (como NOT NULL, UNIQUE, CHECK, FOREIGN KEY) estejam implementadas corretamente.

- Validar se as relações entre as tabelas (one-to-many, many-to-many) estão bem definidas e consistentes com a lógica de negócio.

### Documentação:

- Atualizar a documentação do banco de dados, incluindo o diagrama ER atualizado.

- Criar um DML com dados fictícios para testar e validar o banco de dados.

### Revisão da Estrutura do Banco de Dados:

- [x] Verificar a normalização das tabelas (até a 3ª forma normal).

- [x] Validar tipos de dados e relações entre as tabelas.

- [x] Conferir a definição das chaves primárias e estrangeiras.

### Análise de Índices e Performance:

- [x] Analisar a necessidade de índices adicionais ou remoção de índices desnecessários.

### Consistência e Integridade dos Dados:

- [x] Revisar as restrições de integridade (NOT NULL, UNIQUE, CHECK).

- [x] Validar as relações entre tabelas e ajustes conforme necessário.

### Atualização da Documentação:

- [x] Atualizar o diagrama ER para refletir as últimas mudanças.

- [x] Criar um DML com dados fictícios para testar e validar o banco de dados.

**Comment by JulioAraujo92** [comment]
### Revisão da Estrutura de Banco de Dados

### Primeira Forma Normal (1NF)
A 1NF exige que:
Todos os valores sejam atômicos (sem conjuntos ou listas).
Cada campo tenha um valor único por linha.

**Todas as tabelas atendem a essa norma, pois os campos armazenam valores atômicos e não há listas ou conjuntos.**

### Segunda Forma Normal (2NF)
A 2NF exige que:
A tabela esteja na 1NF.
Todos os atributos não chave sejam totalmente dependentes da chave primária.

**Como todas as tabelas com chaves compostas têm dependências funcionais completas em relação às chaves primárias, estão de acordo com a 2NF.**

### Terceira Forma Normal (3NF)
A 3NF exige que:
A tabela esteja na 2NF.
Não haja dependência transitiva entre atributos não chave.

**Source: Atende à 3NF, pois cada campo depende diretamente da chave primária src_cod.
Map_source: Atende à 3NF. map_author, map_body, map_title, e map_date dependem diretamente de map_id.
Tag: Atende à 3NF, pois tag_name depende apenas de tag_cod.
Source_tag: Atende à 3NF, pois src_cod e tag_cod dependem diretamente de src_tag_cod.
News: Atende à 3NF. Todos os atributos dependem diretamente da chave primária new_cod, sem dependências transitivas.
News_tag: Atende à 3NF, pois new_cod e src_tag_cod dependem diretamente da chave composta (new_cod, src_tag_cod).
News_author: Atende à 3NF. new_aut_name depende diretamente de new_aut_id.
Text: Atende à 3NF, pois text_description depende diretamente de text_cod.
Synonymous: Atende à 3NF. text_cod e syn_group compõem a chave primária e estão corretamente relacionados sem dependências transitivas.**



### Criar um DML com dados fictícios para testar e validar o banco de dados.

-- Tabela Source
INSERT INTO Source (src_name, src_type, src_address) VALUES
('Agência Brasil', '1', 'https://agenciabrasil.ebc.com.br'),
('Reuters', '1', 'https://www.reuters.com'),
('New York Times', '2', 'https://www.nytimes.com');

-- Tabela Map_source
INSERT INTO Map_source (src_cod, map_author, map_body, map_title, map_date) VALUES
(1, 'João Silva', 'Texto do mapa da notícia 1...', 'Mapa de Agricultura', '2024-10-01'),
(2, 'Maria Costa', 'Texto do mapa da notícia 2...', 'Mapa de Economia', '2024-10-05'),
(3, 'Paulo Mendes', 'Texto do mapa da notícia 3...', 'Mapa de Política', '2024-10-10');

-- Tabela Tag
INSERT INTO Tag (tag_name) VALUES
('Agricultura'),
('Economia'),
('Política'),
('Tecnologia');

-- Tabela Source_tag
INSERT INTO Source_tag (src_cod, tag_cod) VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 4);

-- Tabela News_author
INSERT INTO News_author (new_aut_name) VALUES
('Carlos Oliveira'),
('Fernanda Martins'),
('Ana Souza');

-- Tabela News
INSERT INTO News (new_title, new_registry_date, new_aut_cod, new_src_cod, new_address) VALUES
('Colheita da Mandioca Cresce em 2024', '2024-10-15', 1, 1, 'https://agenciabrasil.ebc.com.br/agricultura/colheita-mandioca-2024'),
('Inflação cai em setembro', '2024-10-18', 2, 2, 'https://www.reuters.com/economia/inflacao-cai-setembro'),
('Eleições presidenciais 2024', '2024-10-20', 3, 3, 'https://www.nytimes.com/politics/eleicoes-2024');

-- Tabela News_tag
INSERT INTO News_tag (new_cod, src_tag_cod) VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 4);

-- Tabela Text
INSERT INTO Text (text_cod, text_description) VALUES
(1, 'colheita'),
(2, 'mandioca'),
(3, 'produção'),
(4, 'agrícola');

-- Tabela Synonymous
INSERT INTO Synonymous (text_cod, syn_group) VALUES
(1, 1),
(2, 1),
(3, 2),
(4, 2);
